services:
  - type: web
    name: coral-cloud-pms-graphql
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: OAUTH_CLIENT_ID
        generateValue: true
      - key: OAUTH_CLIENT_SECRET
        generateValue: true
      - key: BASIC_AUTH_USER
        value: datacloud
      - key: BASIC_AUTH_PASSWORD
        generateValue: true
